codecov:
    notify:
        require_ci_to_pass: yes

coverage:
    status:
        project:
            default:
                # basic
                target: 100%
                threshold: null
                base: auto
                flags: null
                paths: null
                # advanced
                branches: null
                if_not_found: success
                if_ci_failed: error
                informational: False
                only_pulls: false

    ignore:
        - "src/main/java/com/techswitch/ispy/config/AppConfig.java"
        - "main/java/com/techswitch/ispy/config/AppConfig.java"
        - "java/com/techswitch/ispy/config/AppConfig.java"
        - "com/techswitch/ispy/config/AppConfig.java"
        - "techswitch/ispy/config/AppConfig.java"
        - "ispy/config/AppConfig.java"
        - "config/AppConfig.java"