coverage:
    range: 70..100
    round: down
    status:
        project:
            default:
                target: 100%
        patch:
            default:
                target: 100%
ignore:
    - "src/main/java/com/techswitch/ispy/config/AppConfig.java"
    - "src/main/java/com/techswitch/ispy/ISpyApplication.java"
